backend:
  name: github
  repo: bastionbc2024-hub/bastion-bc # Ваша адреса на GitHub
  branch: main # Перевірте, чи ваша гілка називається main (або master)

media_folder: "assets/images" # Куди будуть завантажуватися картинки
public_folder: "/assets/images"

collections:
  - name: "pages"
    label: "Сторінки"
    files:
      - label: "Головна"
        name: "index"
        file: "index.html"
        fields:
          - {label: "Заголовок сторінки", name: "title", widget: "string"}
          - {label: "Основний контент", name: "body", widget: "markdown"}
